apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-batch-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/mysql-batch"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-batch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  volumeName: mysql-batch-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-batch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-batch
  template:
    metadata:
      labels:
        app: mysql-batch
    spec:
      containers:
        - name: mysql-batch
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_ROOT_HOST
              value: "%"
            - name: MYSQL_DATABASE
              value: batch_db
            - name: MYSQL_USER
              value: batch_user
            - name: MYSQL_PASSWORD
              value: batch_pass
          resources:
            limits:
              memory: "812Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: mysql-batch-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-batch-data
          persistentVolumeClaim:
            claimName: mysql-batch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-batch-service
spec:
  type: NodePort
  selector:
    app: mysql-batch
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30333