apiVersion: v1
kind: ConfigMap
metadata:
  name: ravo-backend-configmap
data:
  # Datasource URLs
  SPRING_DATASOURCE_BATCH_JDBC_URL: "jdbc:mysql://***.***.***.***:****/batch_db?allowPublicKeyRetrieval=true&useSSL=false"
  SPRING_DATASOURCE_BATCH_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  
  SPRING_DATASOURCE_ACTIVE_JDBC_URL: "jdbc:mysql://default-direct-mysql-act-b9cad-111356016-9b0b2cd4e77e.kr.lb.naverncp.com:****/ravo_db?allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_ACTIVE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  
  SPRING_DATASOURCE_STANDBY_JDBC_URL: "jdbc:mysql://***.***.***.***:****/ravo_db?allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_STANDBY_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"


  # Kafka
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "***.***.***.***:****"
  SPRING_KAFKA_CONSUMER_GROUP_ID: "ravo-live-sync-group"
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: "earliest"


  # Spring Batch
  SPRING_BATCH_JDBC_INITIALIZE_SCHEMA: "always"
  SPRING_BATCH_JOB_ENABLED: "true"
  SPRING_BATCH_JOB_NAME: "coldStandbyBackupJob"


  # JPA
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQLDialect"


  # Application - Database
  APPLICATION_DATABASE_ACTIVE_HOST: "default-direct-mysql-act-b9cad-111356016-9b0b2cd4e77e.kr.lb.naverncp.com"
  APPLICATION_DATABASE_ACTIVE_PORT: "3416"
  APPLICATION_DATABASE_ACTIVE_DATABASE: "ravo_db"
  APPLICATION_DATABASE_ACTIVE_DRIVERCLASSNAME: "mysql"
  APPLICATION_DATABASE_STANDBY_HOST: "***.***.***.***"
  APPLICATION_DATABASE_STANDBY_PORT: "3317"
  APPLICATION_DATABASE_STANDBY_DATABASE: "ravo_db"
  APPLICATION_DATABASE_STANDBY_DRIVERCLASSNAME: "mysql"


  # Application - Endpoints
  APPLICATION_FAILOVER_STATUS_URL: "http://***.***.***.***:****/status"
  APPLICATION_FAILOVER_RECOVER_URL: "http://***.***.***.***:****/recover"
  APPLICATION_MANAGER_UI_LOCK_URL: "http://default-ravo-agent-servi-75463-111435310-3cc24a00c866.kr.lb.naverncp.com:****/ui/lock"
  APPLICATION_MANAGER_UI_UNLOCK_URL: "http://default-ravo-agent-servi-75463-111435310-3cc24a00c866.kr.lb.naverncp.com:****/ui/unlock"


  # Management
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"


  # Backup
  BACKUP_OUTPUT_DIR: "/opt/ravo/backup"
  BACKUP_CRON: "0 0 2 * * *"


  # Ravo Live Sync
  RAVO_LIVE_SYNC_LISTENER_ID: "active-change-consumer"
  RAVO_LIVE_SYNC_TOPIC_PATTERN: "'ravo_db.ravo_db.(transactions|users)$'"


  # 연결 타임아웃 증가
  SPRING_DATASOURCE_BATCH_HIKARI_CONNECTION_TIMEOUT: "30000"
  SPRING_DATASOURCE_BATCH_HIKARI_MAXIMUM_POOL_SIZE: "10"
  SPRING_DATASOURCE_BATCH_HIKARI_MINIMUM_IDLE: "2"


  # 연결 테스트 설정
  SPRING_DATASOURCE_BATCH_HIKARI_CONNECTION_TEST_QUERY: "SELECT 1"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ravo-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ravo-backend
  template:
    metadata:
      labels:
        app: ravo-backend
    spec:
      containers:
      - name: ravo-backend
        image: judemin/ravo-server:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080 # Actuator/Management Endpoints
        envFrom:
        - configMapRef:
            name: ravo-backend-configmap
        env:
          # === Secret에서 민감 정보 주입 ===
          # Batch DB Credentials
          - name: SPRING_DATASOURCE_BATCH_USERNAME
            valueFrom:
              secretKeyRef:
                name: ravo-backend-secret
                key: DB_USERNAME
          - name: SPRING_DATASOURCE_BATCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ravo-backend-secret
                key: DB_PASSWORD_BATCH


          # Active DB Credentials
          - name: SPRING_DATASOURCE_ACTIVE_USERNAME
            valueFrom:
              secretKeyRef:
                name: ravo-backend-secret
                key: DB_USERNAME
          - name: SPRING_DATASOURCE_ACTIVE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ravo-backend-secret
                key: DB_PASSWORD
          
          # Standby DB Credentials
          - name: SPRING_DATASOURCE_STANDBY_USERNAME
            valueFrom:
              secretKeyRef:
                name: ravo-backend-secret
                key: DB_USERNAME
          - name: SPRING_DATASOURCE_STANDBY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ravo-backend-secret
                key: DB_PASSWORD


          # Application Database Active Credentials
          - name: APPLICATION_DATABASE_ACTIVE_USERNAME
            valueFrom:
              secretKeyRef:
                name: ravo-backend-secret
                key: DB_USERNAME
          - name: APPLICATION_DATABASE_ACTIVE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ravo-backend-secret
                key: DB_PASSWORD
                
          # Application Database Standby Credentials
          - name: APPLICATION_DATABASE_STANDBY_USERNAME
            valueFrom:
              secretKeyRef:
                name: ravo-backend-secret
                key: DB_USERNAME
          - name: APPLICATION_DATABASE_STANDBY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ravo-backend-secret
                key: DB_PASSWORD


---
apiVersion: v1
kind: Secret
metadata:
  name: ravo-backend-secret
type: Opaque
stringData:  # base64 인코딩 불필요
  DB_USERNAME: ********
  DB_PASSWORD: ********
  DB_PASSWORD_BATCH: ********


---
apiVersion: v1
kind: Service
metadata:
  name: ravo-backend-service
spec:
  type: NodePort
  selector:
    app: ravo-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30456
