replicaCount: 1
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Kafka 접속 정보
kafkaServer:
  - kafka.kafka.svc.cluster.local:9092

rbac:
  create: true

# Prometheus Scrape
serviceMonitor:
  enabled: true
  namespace: monitoring
  labels:
    release: prometheus-stack