# K-PaaS 내 외부 Standby DB를 위한 Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-standby-endpoint
spec:
  ports:
  - protocol: TCP
    port: 3306 # 서비스 포트는 내부 Active DB와 동일하게 맞출 수 있음
    targetPort: 3317 # 실제 외부 Standby DB의 포트

---
# 위 Service에 외부 IP를 매핑하는 Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-standby-endpoint
subsets:
  - addresses:
      - ip: "<On-Prem Public IP>"
    ports:
      - port: 3317
        protocol: TCP