apiVersion: apps/v1
kind: Deployment
metadata:
  name: ravo-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ravo-manager
  template:
    metadata:
      labels:
        app: ravo-manager
    spec:
      containers:
      - name: ravo-manager
        image: judemin/ravo-manager:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        env:
          # === ConfigMap에서 설정값 주입 ===
          # DB URLs (수정: 대시를 언더스코어로 변경)
          - name: SPRING_DATASOURCE_LIVE_JDBC_URL
            valueFrom:
              configMapKeyRef:
                name: ravo-manager-configmap
                key: LIVE_DB_URL
          - name: SPRING_DATASOURCE_STANDBY_JDBC_URL
            valueFrom:
              configMapKeyRef:
                name: ravo-manager-configmap
                key: STANDBY_DB_URL
          - name: SPRING_DATASOURCE_BATCH_JDBC_URL
            valueFrom:
              configMapKeyRef:
                name: ravo-manager-configmap
                key: BATCH_DB_URL
          - name: SPRING_DATASOURCE_DIRECT_JDBC_URL
            valueFrom:
              configMapKeyRef:
                name: ravo-manager-configmap
                key: DIRECT_DB_URL

          # Monitoring Endpoints
          - name: MONITORING_ENDPOINTS_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: ravo-manager-configmap
                key: MONITORING_ACTIVE_URL
          - name: MONITORING_ENDPOINTS_STANDBY
            valueFrom:
              configMapKeyRef:
                name: ravo-manager-configmap
                key: MONITORING_STANDBY_URL

          # Application Endpoints
          - name: APPLICATION_FAILOVER_STATUS_URL
            valueFrom:
              configMapKeyRef:
                name: ravo-manager-configmap
                key: FAILOVER_STATUS_URL
          - name: CLIENT_ENDPOINTS_SCALE_DOWN
            valueFrom:
              configMapKeyRef:
                name: ravo-manager-configmap
                key: CLIENT_SCALE_DOWN_URL
          - name: CLIENT_ENDPOINTS_SCALE_UP
            valueFrom:
              configMapKeyRef:
                name: ravo-manager-configmap
                key: CLIENT_SCALE_UP_URL

          # Management
          - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
            valueFrom:
              configMapKeyRef:
                name: ravo-manager-configmap
                key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE

          # === Secret에서 민감 정보 주입 ===
          # Live DB Credentials
          - name: SPRING_DATASOURCE_LIVE_USERNAME
            valueFrom:
              secretKeyRef:
                name: ravo-manager-secret
                key: DB_USERNAME
          - name: SPRING_DATASOURCE_LIVE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ravo-manager-secret
                key: DB_PASSWORD

          # Standby DB Credentials
          - name: SPRING_DATASOURCE_STANDBY_USERNAME
            valueFrom:
              secretKeyRef:
                name: ravo-manager-secret
                key: DB_USERNAME
          - name: SPRING_DATASOURCE_STANDBY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ravo-manager-secret
                key: DB_PASSWORD

          # Batch DB Credentials
          - name: SPRING_DATASOURCE_BATCH_USERNAME
            valueFrom:
              secretKeyRef:
                name: ravo-manager-secret
                key: DB_USERNAME
          - name: SPRING_DATASOURCE_BATCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ravo-manager-secret
                key: DB_PASSWORD_BATCH

          # Direct DB Credentials
          - name: SPRING_DATASOURCE_DIRECT_USERNAME
            valueFrom:
              secretKeyRef:
                name: ravo-manager-secret
                key: DB_USERNAME
          - name: SPRING_DATASOURCE_DIRECT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ravo-manager-secret
                key: DB_PASSWORD
